export const books = [
  {
    id: "1",
    url: "https://source.unsplash.com/random/?book",
    Book: "Data Science",
    Writer: "James Hooks",
    No_of_Books: "10",
    Available_Books: "5",
  },
  {
    id: "2",
    url: "https://source.unsplash.com/random/?book",
    Book: "Machine Learning",
    Writer: "Sarah Johnson",
    No_of_Books: "8",
    Available_Books: "3",
  },
  {
    id: "3",
    url: "https://source.unsplash.com/random/?book",
    Book: "Python Programming",
    Writer: "John Smith",
    No_of_Books: "12",
    Available_Books: "7",
  },
  {
    id: "4",
    url: "https://source.unsplash.com/random/?book",
    Book: "Deep Learning",
    Writer: "Michael Brown",
    No_of_Books: "15",
    Available_Books: "9",
  },
  {
    id: "5",
    url: "https://source.unsplash.com/random/?book",
    Book: "Web Development",
    Writer: "Emma White",
    No_of_Books: "18",
    Available_Books: "12",
  },
  {
    id: "6",
    url: "https://source.unsplash.com/random/?book",
    Book: "JavaScript Basics",
    Writer: "David Lee",
    No_of_Books: "10",
    Available_Books: "4",
  },
  {
    id: "7",
    url: "https://source.unsplash.com/random/?book",
    Book: "Algorithms",
    Writer: "Alice Green",
    No_of_Books: "20",
    Available_Books: "15",
  },
  {
    id: "8",
    url: "https://source.unsplash.com/random/?book",
    Book: "Computer Networks",
    Writer: "Tom Brown",
    No_of_Books: "14",
    Available_Books: "8",
  },
  {
    id: "9",
    url: "https://source.unsplash.com/random/?book",
    Book: "Artificial Intelligence",
    Writer: "Olivia Adams",
    No_of_Books: "16",
    Available_Books: "11",
  },
  {
    id: "10",
    url: "https://source.unsplash.com/random/?book",
    Book: "Databases",
    Writer: "Ethan Wilson",
    No_of_Books: "22",
    Available_Books: "18",
  },
  {
    id: "11",
    url: "https://source.unsplash.com/random/?book",
    Book: "Software Engineering",
    Writer: "Sophia Martinez",
    No_of_Books: "10",
    Available_Books: "6",
  },
  {
    id: "12",
    url: "https://source.unsplash.com/random/?book",
    Book: "Operating Systems",
    Writer: "Jack Anderson",
    No_of_Books: "18",
    Available_Books: "13",
  },
  {
    id: "13",
    url: "https://source.unsplash.com/random/?book",
    Book: "C++ Programming",
    Writer: "Lily Hall",
    No_of_Books: "12",
    Available_Books: "9",
  },
  {
    id: "14",
    url: "https://source.unsplash.com/random/?book",
    Book: "Art",
    Writer: "Daniel Adams",
    No_of_Books: "9",
    Available_Books: "4",
  },
  {
    id: "15",
    url: "https://source.unsplash.com/random/?book",
    Book: "History",
    Writer: "Natalie Moore",
    No_of_Books: "25",
    Available_Books: "20",
  },
  {
    id: "16",
    url: "https://source.unsplash.com/random/?book",
    Book: "Mathematics",
    Writer: "Jason King",
    No_of_Books: "30",
    Available_Books: "25",
  },
  {
    id: "17",
    url: "https://source.unsplash.com/random/?book",
    Book: "Physics",
    Writer: "Grace Thomas",
    No_of_Books: "20",
    Available_Books: "16",
  },
  {
    id: "18",
    url: "https://source.unsplash.com/random/?book",
    Book: "Chemistry",
    Writer: "Lucas Turner",
    No_of_Books: "15",
    Available_Books: "10",
  },
  {
    id: "19",
    url: "https://source.unsplash.com/random/?book",
    Book: "Biology",
    Writer: "Ava Rodriguez",
    No_of_Books: "20",
    Available_Books: "17",
  },
  {
    id: "20",
    url: "https://source.unsplash.com/random/?book",
    Book: "Literature",
    Writer: "Ryan Garcia",
    No_of_Books: "18",
    Available_Books: "14",
  },
  {
    id: "21",
    url: "https://source.unsplash.com/random/?book",
    Book: "Economics",
    Writer: "Isabella Martinez",
    No_of_Books: "14",
    Available_Books: "11",
  },
  {
    id: "22",
    url: "https://source.unsplash.com/random/?book",
    Book: "Philosophy",
    Writer: "Mia Hernandez",
    No_of_Books: "12",
    Available_Books: "8",
  },
  {
    id: "23",
    url: "https://source.unsplash.com/random/?book",
    Book: "Psychology",
    Writer: "Alexander Young",
    No_of_Books: "16",
    Available_Books: "12",
  },
  {
    id: "24",
    url: "https://source.unsplash.com/random/?book",
    Book: "Sociology",
    Writer: "Samantha Adams",
    No_of_Books: "18",
    Available_Books: "15",
  },
  {
    id: "25",
    url: "https://source.unsplash.com/random/?book",
    Book: "Political Science",
    Writer: "Joseph Wilson",
    No_of_Books: "20",
    Available_Books: "18",
  },
  {
    id: "26",
    url: "https://source.unsplash.com/random/?book",
    Book: "Geography",
    Writer: "Evelyn Perez",
    No_of_Books: "14",
    Available_Books: "9",
  },
  // {
  //   id: "27",
  //   url: "https://source.unsplash.com/random/?book",
  //   Book: "Anthropology",
  //   Writer: "Andrew Garcia",
  //   No_of_Books: "12",
  //   Available_Books: "10",
  // },
  // {
  //   id: "28",
  //   url: "https://source.unsplash.com/random/?book",
  //   Book: "Fine Arts",
  //   Writer: "Madison Brown",
  //   No_of_Books: "10",
  //   Available_Books: "7",
  // },
  // {
  //   id: "29",
  //   url: "https://source.unsplash.com/random/?book",
  //   Book: "Music",
  //   Writer: "Nicholas Martinez",
  //   No_of_Books: "16",
  //   Available_Books: "12",
  // },
  // {
  //   id: "30",
  //   url: "https://source.unsplash.com/random/?book",
  //   Book: "Health",
  //   Writer: "Chloe Wilson",
  //   No_of_Books: "20",
  //   Available_Books: "18",
  // },
];
