export const data_one = [
  {
    id: 1,
    sl: 1,
    books: "Data science",
    authors: "James Harith",
    request: "2024-03-20",
    remark: "Request",
    // request: "renew",
  },
  {
    id: 2,
    sl: 2,
    books: "Data science",
    authors: "James Harith",
    request: "2024-03-20",
    remark: "Added",
    // request: "renew",
  },
  {
    id: 3,
    sl: 3,
    books: "Data science",
    authors: "James Harith",
    request: "2024-03-20",
    remark: "Request",
    // request: "renew",
  },
  {
    id: 4,
    sl: 4,
    books: "Data science",
    authors: "James Harith",
    request: "2024-03-20",
    remark: "Added",
    // request: "renew",
  },
  {
    id: 5,
    sl: 5,
    books: "Data science",
    authors: "James Harith",
    request: "2024-03-20",
    remark: "Request",
    // request: "renew",
  },
];
